import type { CountryCode } from "@/lib/countries";
import type { Level } from "@/modules/cost/data";

/**
 * A starter catalogue.
 *
 * Institution names, cities and the courses they run are public fact. Tuition
 * and entry requirements are INDICATIVE and move every intake. The screen says
 * so, and every row links out to the university's own page, which is the only
 * figure anyone should act on.
 *
 * Consultancies extend this with the institutions they actually have
 * agreements with. Adding one is adding a line.
 */
export type Uni = {
  id: string;
  name: string;
  city: string;
  country: CountryCode;
  levels: Level[];
  fields: string[];
  /** Indicative annual tuition in the destination currency. */
  tuitionLow: number;
  tuitionHigh: number;
  /** Typical minimum overall IELTS. */
  ielts: number;
  /** Typical minimum, as a percentage of the local marking scale. */
  minPercent: number;
  intakes: string[];
  site: string;
  note?: string;
};

export const UNIVERSITIES: Uni[] = [
  // ---------------------------------------------------------------- Australia
  { id: "au-melbourne", name: "University of Melbourne", city: "Melbourne", country: "AU", levels: ["bachelors", "masters"], fields: ["Business", "Engineering", "IT", "Science", "Health"], tuitionLow: 45000, tuitionHigh: 58000, ielts: 6.5, minPercent: 75, intakes: ["February", "July"], site: "https://www.unimelb.edu.au", note: "Group of Eight. Competitive entry and priced accordingly." },
  { id: "au-sydney", name: "University of Sydney", city: "Sydney", country: "AU", levels: ["bachelors", "masters"], fields: ["Business", "Engineering", "IT", "Health", "Science"], tuitionLow: 46000, tuitionHigh: 60000, ielts: 6.5, minPercent: 75, intakes: ["February", "August"], site: "https://www.sydney.edu.au", note: "Group of Eight." },
  { id: "au-monash", name: "Monash University", city: "Melbourne", country: "AU", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Business", "Nursing", "Science"], tuitionLow: 42000, tuitionHigh: 55000, ielts: 6.5, minPercent: 70, intakes: ["February", "July"], site: "https://www.monash.edu", note: "Group of Eight, and takes more international students than most of them." },
  { id: "au-adelaide", name: "University of Adelaide", city: "Adelaide", country: "AU", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Business", "Agriculture", "Health"], tuitionLow: 40000, tuitionHigh: 52000, ielts: 6.5, minPercent: 70, intakes: ["February", "July"], site: "https://www.adelaide.edu.au", note: "Adelaide carries regional benefits despite being a capital." },
  { id: "au-macquarie", name: "Macquarie University", city: "Sydney", country: "AU", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Engineering", "Media"], tuitionLow: 38000, tuitionHigh: 48000, ielts: 6.5, minPercent: 65, intakes: ["February", "July"], site: "https://www.mq.edu.au" },
  { id: "au-rmit", name: "RMIT University", city: "Melbourne", country: "AU", levels: ["diploma", "bachelors", "masters"], fields: ["IT", "Engineering", "Design", "Business"], tuitionLow: 38000, tuitionHigh: 48000, ielts: 6.5, minPercent: 65, intakes: ["February", "July"], site: "https://www.rmit.edu.au" },
  { id: "au-uts", name: "University of Technology Sydney", city: "Sydney", country: "AU", levels: ["bachelors", "masters"], fields: ["IT", "Engineering", "Business", "Health"], tuitionLow: 40000, tuitionHigh: 50000, ielts: 6.5, minPercent: 68, intakes: ["February", "July"], site: "https://www.uts.edu.au" },
  { id: "au-deakin", name: "Deakin University", city: "Melbourne / Geelong", country: "AU", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Nursing", "Engineering"], tuitionLow: 34000, tuitionHigh: 45000, ielts: 6.5, minPercent: 60, intakes: ["March", "July", "November"], site: "https://www.deakin.edu.au" },
  { id: "au-latrobe", name: "La Trobe University", city: "Melbourne / Bendigo", country: "AU", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Health", "Nursing"], tuitionLow: 33000, tuitionHigh: 42000, ielts: 6.5, minPercent: 60, intakes: ["March", "July"], site: "https://www.latrobe.edu.au", note: "Bendigo and Albury-Wodonga campuses are regional." },
  { id: "au-uow", name: "University of Wollongong", city: "Wollongong", country: "AU", levels: ["bachelors", "masters"], fields: ["IT", "Engineering", "Business", "Nursing"], tuitionLow: 32000, tuitionHigh: 42000, ielts: 6.5, minPercent: 60, intakes: ["February", "July"], site: "https://www.uow.edu.au", note: "Regional postcode, extra post-study work rights." },
  { id: "au-newcastle", name: "University of Newcastle", city: "Newcastle", country: "AU", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Business", "Health"], tuitionLow: 32000, tuitionHigh: 42000, ielts: 6.5, minPercent: 60, intakes: ["February", "July"], site: "https://www.newcastle.edu.au", note: "Regional postcode." },
  { id: "au-griffith", name: "Griffith University", city: "Brisbane / Gold Coast", country: "AU", levels: ["diploma", "bachelors", "masters"], fields: ["IT", "Business", "Health", "Hospitality"], tuitionLow: 32000, tuitionHigh: 42000, ielts: 6.5, minPercent: 60, intakes: ["February", "July"], site: "https://www.griffith.edu.au" },
  { id: "au-qut", name: "Queensland University of Technology", city: "Brisbane", country: "AU", levels: ["bachelors", "masters"], fields: ["IT", "Engineering", "Business", "Health"], tuitionLow: 34000, tuitionHigh: 44000, ielts: 6.5, minPercent: 65, intakes: ["February", "July"], site: "https://www.qut.edu.au" },
  { id: "au-swinburne", name: "Swinburne University of Technology", city: "Melbourne", country: "AU", levels: ["diploma", "bachelors", "masters"], fields: ["IT", "Engineering", "Business", "Design"], tuitionLow: 33000, tuitionHigh: 43000, ielts: 6.0, minPercent: 60, intakes: ["February", "July"], site: "https://www.swinburne.edu.au" },
  { id: "au-cqu", name: "CQUniversity", city: "Rockhampton / Melbourne", country: "AU", levels: ["diploma", "bachelors", "masters"], fields: ["IT", "Business", "Nursing", "Hospitality"], tuitionLow: 26000, tuitionHigh: 34000, ielts: 6.0, minPercent: 50, intakes: ["March", "July", "November"], site: "https://www.cqu.edu.au", note: "Widely used for regional pathways." },
  { id: "au-federation", name: "Federation University Australia", city: "Ballarat", country: "AU", levels: ["diploma", "bachelors", "masters"], fields: ["IT", "Business", "Engineering", "Nursing"], tuitionLow: 26000, tuitionHigh: 33000, ielts: 6.0, minPercent: 50, intakes: ["February", "July"], site: "https://federation.edu.au", note: "Regional." },
  { id: "au-usq", name: "University of Southern Queensland", city: "Toowoomba", country: "AU", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Engineering", "Health"], tuitionLow: 28000, tuitionHigh: 36000, ielts: 6.0, minPercent: 55, intakes: ["February", "July", "November"], site: "https://www.unisq.edu.au", note: "Regional." },
  { id: "au-charles-darwin", name: "Charles Darwin University", city: "Darwin", country: "AU", levels: ["diploma", "bachelors", "masters"], fields: ["IT", "Business", "Nursing", "Engineering"], tuitionLow: 28000, tuitionHigh: 36000, ielts: 6.0, minPercent: 55, intakes: ["February", "July", "November"], site: "https://www.cdu.edu.au", note: "Regional, and popular for that reason." },
  { id: "au-vu", name: "Victoria University", city: "Melbourne", country: "AU", levels: ["diploma", "bachelors", "masters"], fields: ["Business", "IT", "Nursing", "Sport"], tuitionLow: 28000, tuitionHigh: 36000, ielts: 6.0, minPercent: 55, intakes: ["February", "July"], site: "https://www.vu.edu.au" },
  { id: "au-ecu", name: "Edith Cowan University", city: "Perth", country: "AU", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Nursing", "Media"], tuitionLow: 30000, tuitionHigh: 39000, ielts: 6.0, minPercent: 58, intakes: ["February", "July"], site: "https://www.ecu.edu.au", note: "Perth carries regional benefits." },
  { id: "au-curtin", name: "Curtin University", city: "Perth", country: "AU", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Business", "Health"], tuitionLow: 34000, tuitionHigh: 44000, ielts: 6.5, minPercent: 62, intakes: ["February", "July"], site: "https://www.curtin.edu.au" },
  { id: "au-flinders", name: "Flinders University", city: "Adelaide", country: "AU", levels: ["bachelors", "masters"], fields: ["Nursing", "IT", "Business", "Health"], tuitionLow: 32000, tuitionHigh: 41000, ielts: 6.5, minPercent: 60, intakes: ["February", "July"], site: "https://www.flinders.edu.au" },
  { id: "au-unisa", name: "University of South Australia", city: "Adelaide", country: "AU", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Engineering", "Health"], tuitionLow: 33000, tuitionHigh: 42000, ielts: 6.5, minPercent: 62, intakes: ["February", "July"], site: "https://www.unisa.edu.au" },
  { id: "au-utas", name: "University of Tasmania", city: "Hobart / Launceston", country: "AU", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Nursing", "Agriculture"], tuitionLow: 29000, tuitionHigh: 38000, ielts: 6.0, minPercent: 55, intakes: ["February", "July"], site: "https://www.utas.edu.au", note: "Regional across the whole state." },

  // -------------------------------------------------------------- New Zealand
  { id: "nz-auckland", name: "University of Auckland", city: "Auckland", country: "NZ", levels: ["bachelors", "masters"], fields: ["Engineering", "Business", "IT", "Health", "Science"], tuitionLow: 38000, tuitionHigh: 52000, ielts: 6.5, minPercent: 70, intakes: ["February", "July"], site: "https://www.auckland.ac.nz", note: "The country's highest ranked." },
  { id: "nz-aut", name: "Auckland University of Technology", city: "Auckland", country: "NZ", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Engineering", "Hospitality"], tuitionLow: 33000, tuitionHigh: 42000, ielts: 6.0, minPercent: 55, intakes: ["February", "July"], site: "https://www.aut.ac.nz" },
  { id: "nz-massey", name: "Massey University", city: "Palmerston North / Auckland", country: "NZ", levels: ["bachelors", "masters"], fields: ["Agriculture", "Business", "IT", "Aviation"], tuitionLow: 31000, tuitionHigh: 40000, ielts: 6.0, minPercent: 55, intakes: ["February", "July"], site: "https://www.massey.ac.nz" },
  { id: "nz-canterbury", name: "University of Canterbury", city: "Christchurch", country: "NZ", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Science", "Business"], tuitionLow: 34000, tuitionHigh: 44000, ielts: 6.5, minPercent: 62, intakes: ["February", "July"], site: "https://www.canterbury.ac.nz" },
  { id: "nz-otago", name: "University of Otago", city: "Dunedin", country: "NZ", levels: ["bachelors", "masters"], fields: ["Health", "Science", "Business"], tuitionLow: 34000, tuitionHigh: 45000, ielts: 6.5, minPercent: 65, intakes: ["February", "July"], site: "https://www.otago.ac.nz" },
  { id: "nz-waikato", name: "University of Waikato", city: "Hamilton", country: "NZ", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Education"], tuitionLow: 32000, tuitionHigh: 40000, ielts: 6.0, minPercent: 55, intakes: ["February", "July", "November"], site: "https://www.waikato.ac.nz" },
  { id: "nz-lincoln", name: "Lincoln University", city: "Christchurch", country: "NZ", levels: ["bachelors", "masters"], fields: ["Agriculture", "Environment", "Business"], tuitionLow: 30000, tuitionHigh: 38000, ielts: 6.0, minPercent: 55, intakes: ["February", "July"], site: "https://www.lincoln.ac.nz" },
  { id: "nz-vuw", name: "Victoria University of Wellington", city: "Wellington", country: "NZ", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Science", "Design"], tuitionLow: 33000, tuitionHigh: 43000, ielts: 6.0, minPercent: 60, intakes: ["February", "July"], site: "https://www.wgtn.ac.nz" },

  // --------------------------------------------------------------------- UK
  { id: "uk-manchester", name: "University of Manchester", city: "Manchester", country: "UK", levels: ["bachelors", "masters"], fields: ["Engineering", "Business", "Science", "IT"], tuitionLow: 26000, tuitionHigh: 36000, ielts: 6.5, minPercent: 70, intakes: ["September"], site: "https://www.manchester.ac.uk", note: "Russell Group. Competitive." },
  { id: "uk-leeds", name: "University of Leeds", city: "Leeds", country: "UK", levels: ["bachelors", "masters"], fields: ["Business", "Engineering", "IT", "Health"], tuitionLow: 25000, tuitionHigh: 34000, ielts: 6.5, minPercent: 68, intakes: ["September"], site: "https://www.leeds.ac.uk", note: "Russell Group." },
  { id: "uk-birmingham", name: "University of Birmingham", city: "Birmingham", country: "UK", levels: ["bachelors", "masters"], fields: ["Business", "Engineering", "Health", "Science"], tuitionLow: 25000, tuitionHigh: 34000, ielts: 6.5, minPercent: 68, intakes: ["September"], site: "https://www.birmingham.ac.uk", note: "Russell Group." },
  { id: "uk-glasgow", name: "University of Glasgow", city: "Glasgow", country: "UK", levels: ["bachelors", "masters"], fields: ["Engineering", "Business", "Science", "Health"], tuitionLow: 24000, tuitionHigh: 33000, ielts: 6.5, minPercent: 68, intakes: ["September", "January"], site: "https://www.gla.ac.uk", note: "Russell Group." },
  { id: "uk-northumbria", name: "Northumbria University", city: "Newcastle", country: "UK", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Engineering", "Health"], tuitionLow: 17000, tuitionHigh: 22000, ielts: 6.0, minPercent: 55, intakes: ["January", "September"], site: "https://www.northumbria.ac.uk", note: "One of the most common UK entry points for Nepali students." },
  { id: "uk-coventry", name: "Coventry University", city: "Coventry", country: "UK", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Engineering", "Health"], tuitionLow: 15000, tuitionHigh: 19000, ielts: 6.0, minPercent: 55, intakes: ["January", "May", "September"], site: "https://www.coventry.ac.uk", note: "Three intakes a year, useful if you miss September." },
  { id: "uk-middlesex", name: "Middlesex University", city: "London", country: "UK", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Health", "Media"], tuitionLow: 16000, tuitionHigh: 20000, ielts: 6.0, minPercent: 55, intakes: ["January", "September"], site: "https://www.mdx.ac.uk", note: "London, higher maintenance requirement." },
  { id: "uk-hertfordshire", name: "University of Hertfordshire", city: "Hatfield", country: "UK", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Engineering"], tuitionLow: 15000, tuitionHigh: 18000, ielts: 6.0, minPercent: 55, intakes: ["January", "September"], site: "https://www.herts.ac.uk" },
  { id: "uk-greenwich", name: "University of Greenwich", city: "London", country: "UK", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Engineering"], tuitionLow: 16500, tuitionHigh: 21000, ielts: 6.0, minPercent: 55, intakes: ["January", "September"], site: "https://www.gre.ac.uk", note: "London, higher maintenance requirement." },
  { id: "uk-leeds-beckett", name: "Leeds Beckett University", city: "Leeds", country: "UK", levels: ["bachelors", "masters"], fields: ["Business", "Health", "Sport"], tuitionLow: 15000, tuitionHigh: 18000, ielts: 6.0, minPercent: 55, intakes: ["January", "September"], site: "https://www.leedsbeckett.ac.uk" },
  { id: "uk-teesside", name: "Teesside University", city: "Middlesbrough", country: "UK", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Engineering", "Health"], tuitionLow: 14000, tuitionHigh: 18000, ielts: 6.0, minPercent: 50, intakes: ["January", "May", "September"], site: "https://www.tees.ac.uk", note: "Low cost of living in the north east." },
  { id: "uk-sunderland", name: "University of Sunderland", city: "Sunderland", country: "UK", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Health", "Media"], tuitionLow: 14000, tuitionHigh: 17500, ielts: 6.0, minPercent: 50, intakes: ["January", "September"], site: "https://www.sunderland.ac.uk" },
  { id: "uk-uclan", name: "University of Central Lancashire", city: "Preston", country: "UK", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Health", "Engineering"], tuitionLow: 15000, tuitionHigh: 19000, ielts: 6.0, minPercent: 52, intakes: ["January", "September"], site: "https://www.uclan.ac.uk" },
  { id: "uk-bpp", name: "BPP University", city: "London / Manchester", country: "UK", levels: ["masters"], fields: ["Business", "Accounting", "Law", "Health"], tuitionLow: 13000, tuitionHigh: 18000, ielts: 6.0, minPercent: 50, intakes: ["January", "May", "September"], site: "https://www.bpp.com", note: "Professional and vocational focus, multiple intakes." },
  { id: "uk-ulster", name: "Ulster University", city: "Belfast", country: "UK", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Engineering", "Health"], tuitionLow: 16000, tuitionHigh: 20000, ielts: 6.0, minPercent: 55, intakes: ["January", "September"], site: "https://www.ulster.ac.uk" },
  { id: "uk-dmu", name: "De Montfort University", city: "Leicester", country: "UK", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Engineering", "Design"], tuitionLow: 15500, tuitionHigh: 19000, ielts: 6.0, minPercent: 55, intakes: ["January", "September"], site: "https://www.dmu.ac.uk" },

  // ------------------------------------------------------------------ Ireland
  { id: "ie-ucd", name: "University College Dublin", city: "Dublin", country: "IE", levels: ["bachelors", "masters"], fields: ["Business", "Engineering", "IT", "Science"], tuitionLow: 22000, tuitionHigh: 30000, ielts: 6.5, minPercent: 65, intakes: ["September"], site: "https://www.ucd.ie" },
  { id: "ie-tcd", name: "Trinity College Dublin", city: "Dublin", country: "IE", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Science", "Health"], tuitionLow: 24000, tuitionHigh: 34000, ielts: 6.5, minPercent: 70, intakes: ["September"], site: "https://www.tcd.ie", note: "The most competitive in Ireland." },
  { id: "ie-ul", name: "University of Limerick", city: "Limerick", country: "IE", levels: ["bachelors", "masters"], fields: ["Engineering", "Business", "IT"], tuitionLow: 16000, tuitionHigh: 24000, ielts: 6.5, minPercent: 60, intakes: ["September"], site: "https://www.ul.ie" },
  { id: "ie-dcu", name: "Dublin City University", city: "Dublin", country: "IE", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Engineering", "Data"], tuitionLow: 17000, tuitionHigh: 25000, ielts: 6.5, minPercent: 60, intakes: ["September", "January"], site: "https://www.dcu.ie" },
  { id: "ie-ncirl", name: "National College of Ireland", city: "Dublin", country: "IE", levels: ["bachelors", "masters"], fields: ["IT", "Business", "Data"], tuitionLow: 13000, tuitionHigh: 17000, ielts: 6.0, minPercent: 55, intakes: ["January", "September"], site: "https://www.ncirl.ie" },
  { id: "ie-griffith", name: "Griffith College", city: "Dublin / Cork", country: "IE", levels: ["diploma", "bachelors", "masters"], fields: ["IT", "Business", "Accounting"], tuitionLow: 12000, tuitionHigh: 16000, ielts: 6.0, minPercent: 55, intakes: ["January", "September"], site: "https://www.griffith.ie" },
  { id: "ie-atu", name: "Atlantic Technological University", city: "Galway / Sligo", country: "IE", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Business", "Science"], tuitionLow: 12000, tuitionHigh: 16000, ielts: 6.0, minPercent: 55, intakes: ["September", "January"], site: "https://www.atu.ie" },

  // ---------------------------------------------------------------------- USA
  { id: "us-asu", name: "Arizona State University", city: "Tempe, AZ", country: "US", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Business", "Science"], tuitionLow: 32000, tuitionHigh: 45000, ielts: 6.5, minPercent: 65, intakes: ["January", "August"], site: "https://www.asu.edu" },
  { id: "us-uta", name: "University of Texas at Arlington", city: "Arlington, TX", country: "US", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Business"], tuitionLow: 24000, tuitionHigh: 32000, ielts: 6.5, minPercent: 60, intakes: ["January", "August"], site: "https://www.uta.edu", note: "A long-standing destination for Nepali students." },
  { id: "us-utd", name: "University of Texas at Dallas", city: "Richardson, TX", country: "US", levels: ["masters"], fields: ["IT", "Engineering", "Business", "Data"], tuitionLow: 28000, tuitionHigh: 38000, ielts: 6.5, minPercent: 65, intakes: ["January", "August"], site: "https://www.utdallas.edu" },
  { id: "us-wichita", name: "Wichita State University", city: "Wichita, KS", country: "US", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Health"], tuitionLow: 18000, tuitionHigh: 25000, ielts: 6.0, minPercent: 55, intakes: ["January", "August"], site: "https://www.wichita.edu" },
  { id: "us-uco", name: "University of Central Oklahoma", city: "Edmond, OK", country: "US", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Education"], tuitionLow: 16000, tuitionHigh: 22000, ielts: 6.0, minPercent: 55, intakes: ["January", "August"], site: "https://www.uco.edu" },
  { id: "us-southeast-missouri", name: "Southeast Missouri State University", city: "Cape Girardeau, MO", country: "US", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Engineering Tech"], tuitionLow: 15000, tuitionHigh: 20000, ielts: 6.0, minPercent: 50, intakes: ["January", "August"], site: "https://www.semo.edu", note: "Among the more affordable options." },
  { id: "us-troy", name: "Troy University", city: "Troy, AL", country: "US", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Nursing"], tuitionLow: 15000, tuitionHigh: 20000, ielts: 6.0, minPercent: 50, intakes: ["January", "May", "August"], site: "https://www.troy.edu" },
  { id: "us-uic", name: "University of Illinois Chicago", city: "Chicago, IL", country: "US", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Health", "Business"], tuitionLow: 30000, tuitionHigh: 40000, ielts: 6.5, minPercent: 65, intakes: ["January", "August"], site: "https://www.uic.edu" },
  { id: "us-umkc", name: "University of Missouri–Kansas City", city: "Kansas City, MO", country: "US", levels: ["bachelors", "masters"], fields: ["IT", "Engineering", "Business", "Health"], tuitionLow: 20000, tuitionHigh: 28000, ielts: 6.0, minPercent: 55, intakes: ["January", "August"], site: "https://www.umkc.edu" },

  // ------------------------------------------------------------------- Canada
  { id: "ca-conestoga", name: "Conestoga College", city: "Kitchener, ON", country: "CA", levels: ["diploma", "bachelors"], fields: ["IT", "Business", "Engineering Tech", "Health"], tuitionLow: 16000, tuitionHigh: 22000, ielts: 6.0, minPercent: 55, intakes: ["January", "May", "September"], site: "https://www.conestogac.on.ca", note: "Check the programme still qualifies for a PGWP." },
  { id: "ca-humber", name: "Humber Polytechnic", city: "Toronto, ON", country: "CA", levels: ["diploma", "bachelors"], fields: ["Business", "IT", "Media", "Hospitality"], tuitionLow: 17000, tuitionHigh: 23000, ielts: 6.0, minPercent: 55, intakes: ["January", "May", "September"], site: "https://humber.ca" },
  { id: "ca-seneca", name: "Seneca Polytechnic", city: "Toronto, ON", country: "CA", levels: ["diploma", "bachelors"], fields: ["IT", "Business", "Engineering Tech", "Health"], tuitionLow: 16500, tuitionHigh: 22000, ielts: 6.0, minPercent: 55, intakes: ["January", "May", "September"], site: "https://www.senecapolytechnic.ca" },
  { id: "ca-george-brown", name: "George Brown College", city: "Toronto, ON", country: "CA", levels: ["diploma", "bachelors"], fields: ["Business", "Health", "Hospitality", "IT"], tuitionLow: 17000, tuitionHigh: 23000, ielts: 6.0, minPercent: 55, intakes: ["January", "May", "September"], site: "https://www.georgebrown.ca" },
  { id: "ca-douglas", name: "Douglas College", city: "New Westminster, BC", country: "CA", levels: ["diploma", "bachelors"], fields: ["Business", "Health", "IT"], tuitionLow: 17000, tuitionHigh: 22000, ielts: 6.5, minPercent: 55, intakes: ["January", "May", "September"], site: "https://www.douglascollege.ca" },
  { id: "ca-langara", name: "Langara College", city: "Vancouver, BC", country: "CA", levels: ["diploma", "bachelors"], fields: ["Business", "IT", "Science"], tuitionLow: 17000, tuitionHigh: 22000, ielts: 6.5, minPercent: 55, intakes: ["January", "May", "September"], site: "https://langara.ca" },
  { id: "ca-uwindsor", name: "University of Windsor", city: "Windsor, ON", country: "CA", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Business"], tuitionLow: 28000, tuitionHigh: 38000, ielts: 6.5, minPercent: 65, intakes: ["January", "May", "September"], site: "https://www.uwindsor.ca" },
  { id: "ca-dalhousie", name: "Dalhousie University", city: "Halifax, NS", country: "CA", levels: ["bachelors", "masters"], fields: ["Engineering", "Science", "Business", "Health"], tuitionLow: 26000, tuitionHigh: 36000, ielts: 6.5, minPercent: 70, intakes: ["September"], site: "https://www.dal.ca" },
  { id: "ca-umanitoba", name: "University of Manitoba", city: "Winnipeg, MB", country: "CA", levels: ["bachelors", "masters"], fields: ["Engineering", "IT", "Agriculture", "Health"], tuitionLow: 20000, tuitionHigh: 28000, ielts: 6.5, minPercent: 65, intakes: ["January", "September"], site: "https://umanitoba.ca", note: "Manitoba has among the more accessible provincial nomination routes." },
  { id: "ca-uregina", name: "University of Regina", city: "Regina, SK", country: "CA", levels: ["bachelors", "masters"], fields: ["Engineering", "Business", "IT", "Science"], tuitionLow: 20000, tuitionHigh: 27000, ielts: 6.5, minPercent: 62, intakes: ["January", "May", "September"], site: "https://www.uregina.ca" },
  { id: "ca-cape-breton", name: "Cape Breton University", city: "Sydney, NS", country: "CA", levels: ["bachelors", "masters"], fields: ["Business", "IT", "Health"], tuitionLow: 19000, tuitionHigh: 26000, ielts: 6.5, minPercent: 58, intakes: ["January", "May", "September"], site: "https://www.cbu.ca", note: "Small city, low living costs, large international intake." },
  { id: "ca-thompson-rivers", name: "Thompson Rivers University", city: "Kamloops, BC", country: "CA", levels: ["diploma", "bachelors", "masters"], fields: ["Business", "IT", "Science", "Tourism"], tuitionLow: 19000, tuitionHigh: 26000, ielts: 6.5, minPercent: 58, intakes: ["January", "September"], site: "https://www.tru.ca" },
];

export const ALL_FIELDS = [...new Set(UNIVERSITIES.flatMap((u) => u.fields))].sort();
